- toolchain/defs.bzl
Sometimes the launcher fails to compile with the following error messsage:
```
error: FileNotFound
```
We cannot reproduce this in a controlled environment, but see it happening in the wild often enough to receive repeated questions.
Since this has been escalated to Zig Software Foundation, the most meaningful thing we can ask our users to do is apply a workaround and wait. Let's do just that.
> launcher miscompilation workaround

- toolchain/defs.bzl
More information in the commit message and
https://github.com/ziglang/zig/issues/14815
> Work around a known race in Zig build system

- MODULE.bazel
This is the first step of enabling bzlmod
> Adding MODULE.bazel

- README.md
- mailing-list-archive.mbox
There will be no more emails coming in there.
This file will be deleted after v2 is released, because it's annoying with `git grep`.
> update mailing list archive

- README.md
We have a new maintainer. Also clarify what they can and cannot do.
> maintainers: update the section

- README.md
> Add FabianHahn to maintainers

- .buildkite/pipeline.yml
- README.md
- ci/test_example
- examples/rules_cc/.bazelrc
- examples/rules_cc/.gitignore
- examples/rules_cc/BUILD.bazel
- examples/rules_cc/WORKSPACE
- examples/rules_cc/hello_world.cc
Add a basic isolated examples for rules_cc, as a starting point for users.
Fixes #15.
> Basic isolated example for rules_cc.

- tools/releaser/main.go
Commit 6a8087eebb1e53f6ac7de4bfdc8596c54b2d2338 added a serious bug: it created a tarball from the file system, rather than from a specific git ref.
We want to create the release from a git tag instead, not the current FS. So roll back to `git archive`, just sanitize its output.
> releaser: use git-archive again

- README.md
- examples/rules_cc/WORKSPACE
https://github.com/bazelbuild/bazel/issues/18374
> Releasing hermetic_cc_toolchain v2.0.0-rc2

- tools/releaser/main.go
Fixes 2 issues:
- `git archive` creates a header with a "special" file that's a PAX comment. Which we want to get rid of in the first place. So ignore that.
- Previously files from `tools/releaser` were taken unversioned. Which is not what we want. Now let's add them via `git archive`, so they are included from the necessary tag.
> releaser: fix pax artifacts

- toolchain/defs.bzl
This adds non-exe aliases to user-facing executables:
:tools/ar  -> :tools/ar.exe
:tools/ld.lld  -> :tools/ld.lld.exe
:tools/lld-link  -> :tools/lld-link.exe
:tools/zig-wrapper  -> :tools/zig-wrapper.exe
... so they can be used in either OSs without caring of the file extension.
> Add windows aliases

- toolchain/defs.bzl
https://github.com/marler8997/zig-unofficial-releases/pull/14
> update zig to 0.11.0-dev.3312+ab37ab33c

- rules/zig_binary.bzl
Output of `zig build-exe` depends on the CPU, making it non-reproducible. With `-mcpu` it's fine.
Similar to #22
> rules:cp : make reproducible

- .buildkite/pipeline.yml
> ci: skip zig-utilities tests

- MODULE.bazel
- toolchain/ext.bzl
Fixed linting issues accidentally introduced by #96
> fixed linting issue

- toolchain/defs.bzl
Sometimes the on-host toolchain may not be detected correctly on OSX[1]. Since we are interested only in a *hermetic* toolchain, we are meant to use cross-compilation mode by invoking `-target`. Let's do it.
[1]: https://github.com/ziglang/zig/issues/13313#issuecomment-1761496151
> zig-wrapper: compile with explicit `-target`

- ci/zig-utils
This works with zig 0.11.0. Also closed
https://github.com/ziglang/zig/issues/14036
> zig-utils: use debug mode in tests

- MODULE.bazel
- README.md
- examples/rules_cc/WORKSPACE
https://github.com/bazelbuild/bazel-central-registry/pull/1314
https://github.com/bazelbuild/bazel/issues/20851
> Releasing hermetic_cc_toolchain v2.2.0

- MODULE.bazel
- README.md
- examples/rules_cc/WORKSPACE
This reverts commit eedd8b6c2f4ac7329007e4f22bfb22116f9540a4.
I merged this one incorrectly.
> Revert "Releasing hermetic_cc_toolchain v2.2.0"

- MODULE.bazel
- README.md
- examples/rules_cc/WORKSPACE
Fix non-existent paths being included in globs by @robinlinden in https://github.com/uber/hermetic_cc_toolchain/pull/145
> Releasing hermetic_cc_toolchain v2.2.1

- toolchain/defs.bzl
Now that we have a proper bug report upstream, we can apply the workaound in the toolchain repository behind the scenes. THanks @nadavwe!
Zig upstream issue: https://github.com/ziglang/zig/issues/18763
> error: FileNotFound workaround

- .bcr/presubmit.yml
- ci/release
Cargo-culting https://github.com/bazelbuild/bazel-central-registry/pull/1387
> bcr: add bazel targets

- .github/workflows/ci.yaml
Otherwise it won't populate cache keys.
> cache: must happen after checkout

- toolchain/private/zig_sdk.bzl
https://ziglang.org/download/0.12.0/release-notes.html
> Upgrade zig to 0.12.0

- MODULE.bazel
- toolchain/ext.bzl
This removes an unnecessary entry from the lockfiles of ruleset users.
> Mark extension as reproducible

- MODULE.bazel
- README.md
- examples/rules_cc/WORKSPACE
> Releasing hermetic_cc_toolchain v3.2.0

- .bcr/presubmit.yml
- MODULE.bazel
- README.md
- examples/rules_cc/WORKSPACE
> Releasing v4.0.0
