README.md, mailing-list-archive.mbox
I will be shutting down ~motiejus/bazel-zig-cc@lists.sr.ht within days. Now that comms are in Slack and github issues/PRs, let's add the archive for historical reference.
It can be opened and read through like this:
mutt -R -f mailing-list-archive.mbox
=> Add the mailing list archive

README.md
Fixing the following error:
```
ERROR: Traceback (most recent call last):
File "/Users/$me/dev/$org/$my_repo/WORKSPACE", line 261, column 104, in <toplevel>
"https://mirror.bazel.build/github.com/uber/bazel-zig-cc/releases/download/{}/{}.tar.gz".format(BAZEL_ZIG_CC_VERSION),
Error in format: No replacement found for index 1
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'toolchain/defs.bzl': no such package '@bazel-zig-cc//toolchain': error loading package 'external': Could not load //external package
```
=> Fixing the url template in readme

README.md
The link to the historic email threads seems to be a good spot for it.
=> Make Project Origin more prominent

README.md
We need to preserve the old mirror URL until the new release is cut.
=> README: fix the download URL

toolchain/defs.bzl
We are using only a single trivial function `paths`, which can be bundled. Makes things like test-zigcc[1] easier: less dependencies to worry about.
[1]: https://git.jakstys.lt/motiejus/test-zig-cc/
=> remove `@bazel_skylib` dependency

ci/test, rules/platform.bzl, test/windows/BUILD
rules/ were never meant to be added to the release. Now that we are not *running* multi-arch binaries, we can remove the infrastructure that was necessary to do so.
I may get back to this -- but we need to dust quite a bit off before that happens.
=> rules/ remove run_under

README.md
The recent repository rename broke the assumption about the repository name.
We will soon (hopefully next week) release v2 with all the occurrences of `bazel-zig-cc` removed, and all of this will be over. Sorry for the confusion/mess until that happens.
Fixes #39
=> README: bring the compat name of `http_archive`

ci/launcher, toolchain/defs.bzl
This log message has been seen in a Github Actions worker:
running <...>/c++ failed: signal: illegal instruction (core dumped)
I conclude that the launcher was compiled on a newer CPU than used on the worker at the time.
Reported-by: mp@edgeless.systems
Fixes #22
=> launcher: use `-mcpu=baseline`

toolchain/defs.bzl, toolchain/launcher.zig
From https://github.com/marler8997/zig-unofficial-releases
I also updated the "Release Process" wiki instructing how to use it.
Long live Mr. Marler!
The launcher got a facelift because of this error:
/code/zig-linux-x86_64-0.11.0-dev.2619+bd3e248c7/lib/std/fmt.zig:2013:9: error: function called at runtime cannot return value at comptime
return &buf;
^~~~~~~~~~~
referenced by:
test.launcher:parseArgs: toolchain/launcher.zig:334:31
remaining reference traces hidden; use '-freference-trace' to see all reference traces
Zig gets confused by the requirement in that test in a runtime context.
=> bump zig sdk to 0.11.0-dev.2619+bd3e248c7

toolchain/private/cc_toolchains.bzl, toolchain/private/defs.bzl, toolchain/zig_toolchain.bzl
When building artifacts for macos, pass the `-Wl,-headerpad_max_install_names` linker option to leave space for modifying things like `rpath`.
The built-in toolchain also does it [here](https://github.com/bazelbuild/bazel/blob/0a10409e90f4f6301c24b3743cce90ad8012a81f/tools/cpp/unix_cc_configure.bzl#L599).
Also fixed an issue where the `.map` files under `glibc-hacks` weren't being included in the list of toolchain files.
=> Re-add linkopts and set -Wl,-headerpad_max_install_names on macos

tools/releaser/main.go
To make bzlMod work.
Test:
$ tar -tvf hermetic_cc_toolchain-v99.0.0.tar.gz | grep MODULE.bazel
-rw-rw-r-- root/root       561 2023-04-24 21:03 MODULE.bazel
=> releaser: add MODULE.bazel

toolchain/zig_toolchain.bzl
Move the `-Wl,-S` parameter to the `strip_debug_symbols` feature which is enabled when a `strip_debug_symbols` build variable is present. This is basically copied from [upstream](https://github.com/bazelbuild/bazel/blob/a92ce14f32218719bc4ad65de5dcafb5832ff6a7/tools/cpp/unix_cc_toolchain_config.bzl#L794-L807).
Bazel automatically sets the `strip_debug_symbols` variable if fastmode is enabled, but now it can be overridden with the `--strip=never` parameter. And now one can use `-c opt --strip=always` to strip symbols without fastbuild mode.
=> Move -Wl,-S to a separate strip_debug_symbols feature

ci/test, toolchain/defs.bzl
This cache directory can be re-used by everything and everyone. There is nothing bazel or hermetic_cc_toolchain specific there. So let's make it clear.
Also, if there are any more zig-based toolchains on top of Bazel or other build systems where they cannot rely on $HOME, but need an absolute path, this feels like a reasonable choice.
=> zig cache dir: move to `/tmp/zig-cache`

toolchain/private/cc_toolchains.bzl, toolchain/private/defs.bzl, toolchain/zig_toolchain.bzl
This PR disables the `supports_dynamic_linker` feature for the generated Windows toolchains. Dynamic linking is only poorly supported in bazel's C++ rules and cause all kinds of problems—see the comments I've added for details. This effectively fixes a Windows regression introduced in 0db5d2d9e6554fd2f0e973ea0dceed5f022defb7. After applying this patch, Windows host and target support works fine on v2.0.0-rc1 for me.
=> disable dynamic linker for Windows targets

README.md, ci/release, tools/releaser/README, tools/releaser/main.go
A few changes:
- Now it will write the right boilerplate to `README.md` and `examples/rules_cc/WORKSPACE`.
- tightened the release tarball: it now will depend only on the file content, but not the specific SHA from which the release is created. This way we can cut a release and update the README of the release tarballs *in the same commit*.
- In an upcoming PR the release script will verify that boilerplate in `README.md` and `examples/rules_cc/WORKSPACE` are up to date. But we need to cut `v2.0.0-rc2` first; which I will do with this release script. I will also update the release process wiki with the added features of this tool.
The releaser tool is intended to be used in two modes:
1. *Making* the release: the target tag does not exist.
2. *CI*: the target tag does exist.
The release …
=> update releaser boilerplate + encourage v2.0.0-rc1

ci/release_boilerplate, tools/releaser/main.go, tools/releaser/main_test.go
This mode will be used that the version and the hash in `README.md` and  `examples/rules_cc/WORKSPACE` are up to date.
=> check-only mode, for v2.0.0-rc2

toolchain/defs.bzl, toolchain/launcher.zig
Zig notably fixes https://github.com/ziglang/zig/issues/14815; also, by @jacobly in
https://github.com/ziglang/zig/issues/14815#issuecomment-1550874385:
> @motiejus to be clear, this unrelated issue is not affected by a cache
> clear, and can be resolved by simply rerunning the build (and not
> getting very unlucky again).
=> bump zig sdk + simplify zig build workaround

.buildkite/pipeline.yml, README.md, ci/zig-wrapper, ci/zig-wrapper-wine64, toolchain/defs.bzl, toolchain/private/cc_toolchains.bzl, toolchain/private/defs.bzl, toolchain/zig-wrapper.zig
launcher: rename to zig-wrapper + passthrough mode
Also remove `ld64.lld`, since it was removed from zig upstream back in 2021: https://github.com/ziglang/zig/commit/0e15205521b9a8c95db3c1714dffe3be1df5cda1
Until today the "launcher" could do one thing well: set the environment variables and exec the `zig c++` command. However, it was clumsy with other subcommands: `ar`, `ld.lld` do not expect the `-target`. So there was this "special case" for subcommands that are not c++, but, for the sake of consistency, needed to be in the top-level repository.
This change leaves only one sub-command for the target, which truly expects a `-target` flag: `c++`. From now:
- all other sub-commands required for the toolchain are in top-level.
- anything that is not needed for the toolhain can be directly …
=> launcher: rename to zig-wrapper + passthrough mode

test/glibc_hacks/BUILD, toolchain/private/defs.bzl
With these diffs one can now run
bazel build //test/...
On Windows.
Tests are not there yet, `target_compatible_with` does not always work as I think it should.
=> tests: windows fine tuning

rules/BUILD, rules/cp.zig, rules/platform.bzl, rules/zig_binary.bzl
Previously `cp` was invoked with zig:
zig run cp.zig -- SRC DST
However, this was reverted in 73db33bab01a365a8be01e8586203fc2e95b9f09 due to races in `zig build-exe`, as described in
https://github.com/ziglang/zig/issues/15860
This approach brings back `cp.zig`, but this time the `cp` binary is pre-compiled before invoking it.
That way Bazel will execute `zig build-exe` only once for that target, that way not hitting the race. As a side-effect, the operation will be faster, because `cp` will now be a single binary, as opposed to bringing the whole zig_sdk together.
=> Replace `cp` with zig implementation: v2

README.md, examples/rules_cc/WORKSPACE
Will merge after https://github.com/bazelbuild/bazel/issues/18530 is mirrored.
=> Releasing hermetic_cc_toolchain v2.0.0

tools/releaser/main.go
The current release contains 3 redundant directories:
$ tar -tf hermetic_cc_toolchain-v2.0.0.tar.gz | grep tools
tools/
tools/releaser/
tools/releaser/data/
This change gets rid of them:
$ tar -tvf hermetic_cc_toolchain-v99.0.0.tar.gz
-rw-rw-r-- 0/0            1120 2000-01-01 02:00 LICENSE
-rw-rw-r-- 0/0             561 2000-01-01 02:00 MODULE.bazel
drwxrwxr-x 0/0               0 2000-01-01 02:00 toolchain/
-rw-rw-r-- 0/0               0 2000-01-01 02:00 toolchain/BUILD
-rw-rw-r-- 0/0             407 2000-01-01 02:00 toolchain/BUILD.sdk.bazel
-rw-rw-r-- 0/0           11180 2000-01-01 02:00 toolchain/defs.bzl
drwxrwxr-x 0/0               0 2000-01-01 02:00 toolchain/libc/
-rw-rw-r-- 0/0             405 2000-01-01 02:00 toolchain/libc/BUILD
-rw-rw-r-- 0/0             300 2000-01-01 02:00 …
=> tools/releaser: remove unnecessary paths

toolchain/zig_toolchain.bzl
When a sanitizer (say, UBSAN via `-fsanitize=undefined`) is turned on, `zig cc` will include absolute paths to some header files, making the artifacts non-reproducible.
This commit strips dirnames from such header files.
Fixes #76
=> UBSAN: strip paths

WORKSPACE, ci/zig-utils, test/c/BUILD, test/cgo/BUILD, test/glibc_hacks/BUILD
2.19 is no longer relevant, as Jessie is a long-time EOL.
This will reduce test duration as a side-effect.
=> tests: remove almost all mentions of glibc 2.19

README.md
bazel.slack.com -> bazelbuild.slack.com
And I wondered why on earth I could log in from one, but not the other machine.
=> Update slack link in README.md

BUILD, MODULE.bazel, toolchain/ext.bzl, tools/gazelle/BUILD
This makes it possible to consume ``hermetic_cc_toolchain`` via ``MODULE.bazel``, in a way that is similar to how it is consumed with ``WORKSPACE``.
This doesn't setup the infrastructure to publish to BCR, so it won't make it available by default. 
This can get used in a ``MODULES.bazel`` like so:
```
bazel_dep(name = "hermetic_cc_toolchain", version = "2.0.0")
toolchains = use_extension("@hermetic_cc_toolchain//toolchain:ext.bzl", "toolchains")
use_repo(toolchains, "zig_sdk")
register_toolchains(
"@zig_sdk//toolchain:linux_amd64_gnu.2.28",
"@zig_sdk//toolchain:linux_arm64_gnu.2.28",
"@zig_sdk//toolchain:darwin_amd64",
"@zig_sdk//toolchain:darwin_arm64",
"@zig_sdk//toolchain:windows_amd64",
"@zig_sdk//toolchain:windows_arm64",
)
archive_override(
module_name = "hermetic_cc_toolchain", …
```
=> Enable bzlmod

toolchain/defs.bzl
This is to pick up https://github.com/ziglang/zig/pull/15827, which is needed to enable this toolchain in tests of rules_go.
@motiejus Should we release a new version of hermetic_cc_toolchain after this? So rules_go can refer to a released version
=> Upgrade zig to 0.11.0-dev.3886+0c1bfe271

.buildkite/pipeline.yml, ci/prepare_git
The "apt-get install" step in "Test zig utilities" was failing, which caused the later test to fail.
Turns out buildkite does not add `set -e` on shell scripts, so we gotta do it.
=> ci: fail early

toolchain/defs.bzl, tools/releaser/main.go, tools/releaser/main_test.go
Zig 0.11.0 is released. Upgrading to the released version exposed some wrong assumptions about URL format. So this PR also fixed those assumptions by using `URL_FORMAT_RELEASE` for released version and determining the mirror URL format from the original one.
=> Upgrade zig to 0.11.0

MODULE.bazel, README.md, examples/rules_cc/WORKSPACE
This was created by running `tools/bazel run //tools/releaser -- -tag v2.1.0`
=> Releasing hermetic_cc_toolchain v2.1.0

MODULE.bazel, README.md, examples/rules_cc/WORKSPACE
This is produced by `bazel run //tools/releaser -- -tag v2.1.1`
=> Releasing hermetic_cc_toolchain v2.1.1

.bcr/presubmit.yml, examples/bzlmod/BUILD.bazel
The unused load caused the CI on Bazel Central repository to fail
=> removing unused load

.bcr/presubmit.yml, .buildkite/pipeline.yml, ci/test_example, examples/bzlmod/MODULE.bazel, tools/releaser/main.go
bzlmod requires a different flag to override external dependencies. We need to parameterize that flag depending on whether an example has bzlmod enabled. With this change, our CI covers the the case of a test module depending on hermetic_cc_toolchain as a `bazel_dep`, pointing to a release archive created from HEAD and running all tests in the test module. Hopefully we can catch issues in our CI, rather than on BCR's CI after a release is cut.
With this change, we no longer run the tests again in BCR's CI and no longer need to include the example in the release archive. We only need to verify that the latest release can be loaded by the [anonymous test module](https://github.com/bazelbuild/bazel-central-registry/blob/main/docs/README.md#anonymous-module-test).
=> Testing bzlmod earlier

MODULE.bazel, README.md, examples/rules_cc/WORKSPACE
This is created by `bazel run //tools/releaser -- -tag v2.1.2`.
It has been successfully published to BCR: https://github.com/bazelbuild/bazel-central-registry/pull/951
=> Releasing hermetic_cc_toolchain v2.1.2

toolchain/defs.bzl
Prior to this, I noticed builds ending up with different digests for the builder fairly often. Stripping those builder binaries manually made them match up; with this patch applied, I was able to have builds be 100% cached when trying 5 times (previously almost every time was a different digest).
=> Strip the zig-builder binary for reproducibility

ci/lint
`read -ra var` followed by `${var[*]}` returns only 1 file for some
reason:
$ read -ra zigfiles < <(echo -e "foo\nbar")
$ echo "${zigfiles[*]}"
foo
$ mapfile -t zigfiles < <(echo -e "foo\nbar")
$ echo "${zigfiles[*]}"
foo bar
=> ci/lint: use mapfile

toolchain/defs.bzl
linker: support `--(no-)undefined-version`: https://github.com/ziglang/zig/pull/18486
=> zig sdk: bump to 0.12.0-dev.2127+fcc0c5ddc

.bazelrc, toolchain/private/defs.bzl
I hit this after updating to v2.2.0 where the new zig sdk only includes a `any-macos-any` include folder.
```
ERROR: Traceback (most recent call last):
File "/home/runner/.cache/bazel/_bazel_runner/a9f0723b1e9e47cd91eaa9d5188be59d/external/zig_sdk/BUILD", line 11, column 14, in <toplevel>
declare_files(
File "/home/runner/.cache/bazel/_bazel_runner/a9f0723b1e9e47cd91eaa9d5188be59d/external/hermetic_cc_toolchain/toolchain/defs.bzl", line 257, column 36, in declare_files
all_includes = [native.glob(["lib/{}/**".format(i)]) for i in target_config.includes]
Error in glob: glob pattern 'lib/libc/include/x86_64-macos.11-none/**' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: …
```
=> Fix non-existent paths being included in globs

toolchain/defs.bzl
Since there was movement on the upstream issue
(https://github.com/ziglang/zig/issues/18763), we can now gather more information. Not removing the cache directory, asking users to collaborate.
=> Bump zig to 0.12.0-dev.2631+3069669bc, ask users to collaborate

examples/bzlmod/.bazelversion, examples/rules_cc/.bazelversion
let's see if this mitigates CI throttling when it can't check for current bazel versions
=> add symlinks to .bazelversion

.bazelrc, .github/workflows/ci.yaml, README.md, ci/test, examples/bzlmod/.bazelrc, examples/rules_cc/.bazelrc, toolchain/defs.bzl
MacOS has a cronjob that deletes files older than 3 days from /tmp. That's not good for zig cache: https://github.com/ziglang/zig/issues/18763
Switch to /var/tmp, which does not seem to be randomly wiped at runtime.
This breaking change means the next hermetic_cc_toolchain will be v3.0.0.
=> MacOS default cache dir: /tmp -> /var/tmp

rules/platform.bzl, test/cgo/BUILD
also remove `platform_test`, that is no longer used.
=> test/cgo: cleanup

MODULE.bazel, README.md, go.mod, go.sum, test/c/BUILD, test/c/c_test.go, test/c/main.c, toolchain/platform/defs.bzl, toolchain/private/defs.bzl, toolchain/zig-wrapper.zig
I would like to be able to compile wasm/wasi with zig + bazel. This adds
a toolchain to be able to do so. Wasm/wasi is a pretty rapidly changing
space, but I've choosen the most specific naming that I could (WASI
preview 1).
I've confirmed this works by running the compiled binary with [wasmtime](https://wasmtime.dev/),
a popular wasm/wasi runtime.
```shell
bazel run --run_under=wasmtime //test/c:which_libc_wasip1_wasm
```
=> Add wasm32-wasi-musl target

toolchain/private/zig_sdk.bzl
Fixes a MachO linker bug: https://github.com/ziglang/zig/issues/19026
=> bump zig to 0.12.0-dev.2824+0b7af2563

.gitattributes, .github/workflows/ci.yaml, ci/test_example, tools/releaser/main.go
Enables example tests on Windows.
=> releaser: fix windows

examples/bzlmod/MODULE.bazel
Update bzlmod example to use released version without override to verify the one from BCR works
=> Update bzlmod example to use released version

MODULE.bazel, ci/release
Mark toolchains registered in this repo as a dev dependency. Users will need to register their own toolchains, like they do in WORKSPACE.
Fixes #181.
=> Mark toolchains registered in our MODULE.bazel as a dev dependency

toolchain/private/defs.bzl
I added support for the `.wasm` extension to bazel last year and I figured it'd be a slightly nicity improvement when targetting wasm.
=> feat: use .wasm artifact name extension

toolchain/private/cc_toolchains.bzl
Currently, having an assembly source file as srcs of a cc_library will fail because compiler files are missing from the sandbox:
```
src/main/tools/process-wrapper-legacy.cc:80: "execvp(external/hermetic_cc_toolchain~~toolchains~zig_sdk/tools/x86_64-linux-gnu.2.36/c++, ...)": No such file or directory
```
This PR fixes that.
=> fix: provide cc_toolchain artifacts required for assembly actions

toolchain/defs.bzl
The linker wrapper is missing from all_files when accessing the toolchain files
=> expose linker

MODULE.bazel, toolchain/defs.bzl, toolchain/ext.bzl
`use_extension()` allows to set `dev_dependency = Ture`.
This needs reflection in returned extension metadata, i.e.,
- `root_module_direct_deps`
- `root_module_direct_dev_deps`.
This PR fixes `root_module_direct_dev_deps` always set to empty list as also `root_module_direct_deps` set with generated repo list to proper values taking into account `dev_dependency` value.
Fixes #210 & Closes #210.
=> fix: dev_dependency

toolchain/private/repositories.bzl
`repository_ctx.attr.exec_platforms` and its values are all frozen. We cannot remove host platforms from them. So when we have this in WORKSPACE:
```starlark
RBE_PLATFORMS = {
"linux": ["amd64", "arm64"],
}
zig_toolchains(
exec_platforms = RBE_PLATFORMS
)
```
Builds would fail on Linux because:
```
File "/home/user/.cache/bazel/_bazel_zplin/391a7464ab75ac3a8cb620cc52c50a30/external/hermetic_cc_toolchain/toolchain/private/repositories.bzl", line 75, column 22, in _zig_sdk_repository_impl
_archs.remove(_arch)
Error in remove: trying to mutate a frozen list value
ERROR: Target parsing failed due to unexpected exception: trying to mutate a frozen list value
```
This PR creates a regular dictionary out of the frozen one so we can remove the host platforms from `exec_platforms`
@birunts  can …
=> Avoid modifying frozen list

toolchain/defs.bzl, toolchain/ext.bzl, toolchain/libc_aware/toolchain/BUILD.bazel.tmpl, toolchain/private/repositories.bzl, toolchain/toolchain/BUILD.bazel.tmpl, toolchain/toolchain/defs.bzl, toolchain/utils.bzl
This will allow toolchains to be configurably more restrictive, e.g. by requiring a setting to be enabled in order to select the hermetic toolchains.
This could be a solution to https://github.com/uber/hermetic_cc_toolchain/issues/205.
=> Add path to add extra settings to toolchains
